export const enum ERouteNames {
  DEFAULT = "/",
  DASHBOARD = "/dashboard",
  PROFILE = "/profile",
  COMMUNITIES = "/communities",
  MESSANGER = "/messenger",
  SETTINGS = "/settings",
  AUTH = "/auth",
  LOGIN = "/auth/login",
  REGISTER = "/auth/register",
  VERIFICATION = "/auth/new-verification",
  RESET_PASSWORD = "/auth/reset-password",
  NEW_PASSWORD = "/auth/new-password",
  TWO_FACTOR = "/auth/two-factor",
}
